apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80      # External port
      targetPort: 3000  # Internal container port
  type: LoadBalancer  # Use "NodePort" if deploying locally
