openapi: 3.0.0
info:
  title: Intelligent Content Recommendation API
  description: API documentation for the Intelligent Content Recommendation Backend.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /recommendations:
    get:
      summary: Get content recommendations
      description: Retrieve a list of recommended content based on user preferences.
      responses:
        '200':
          description: A list of recommended content.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the content.
                    title:
                      type: string
                      description: Title of the content.
                    description:
                      type: string
                      description: Brief description of the content.